// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1itLYSjxmUswmUavkvKJGCyzLQ9bsYg',
    appId: '1:467506084437:web:6139aac3b82f133ea872dc',
    messagingSenderId: '467506084437',
    projectId: 'cv-builder-app-a5893',
    authDomain: 'cv-builder-app-a5893.firebaseapp.com',
    storageBucket: 'cv-builder-app-a5893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWwn9xze0DM9utdzXVumCwU75QbyaEobo',
    appId: '1:467506084437:android:bd1a663aebd1e605a872dc',
    messagingSenderId: '467506084437',
    projectId: 'cv-builder-app-a5893',
    storageBucket: 'cv-builder-app-a5893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxikdIIi6byEpWjPeZCEyr99mDmiR16Rc',
    appId: '1:467506084437:ios:b5261ce5d8713ac4a872dc',
    messagingSenderId: '467506084437',
    projectId: 'cv-builder-app-a5893',
    storageBucket: 'cv-builder-app-a5893.firebasestorage.app',
    iosBundleId: 'com.example.cvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxikdIIi6byEpWjPeZCEyr99mDmiR16Rc',
    appId: '1:467506084437:ios:b5261ce5d8713ac4a872dc',
    messagingSenderId: '467506084437',
    projectId: 'cv-builder-app-a5893',
    storageBucket: 'cv-builder-app-a5893.firebasestorage.app',
    iosBundleId: 'com.example.cvApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1itLYSjxmUswmUavkvKJGCyzLQ9bsYg',
    appId: '1:467506084437:web:f30dd0df7285fa1ea872dc',
    messagingSenderId: '467506084437',
    projectId: 'cv-builder-app-a5893',
    authDomain: 'cv-builder-app-a5893.firebaseapp.com',
    storageBucket: 'cv-builder-app-a5893.firebasestorage.app',
  );
}